apiVersion: v2
appVersion: 0.0.1
name: azure-private-dns-crossplane-resources
description: Azure Private DNS Zone Crossplane Resources
home: https://github.com/giantswarm/azure-private-dns-crossplane-resources
icon: https://s.giantswarm.io/app-icons/azure/1/light.svg
sources:
  - https://github.com/giantswarm/azure-private-dns-crossplane-resources
version: 0.0.1
annotations:
  io.giantswarm.application.team: phoenix
